<a href="https://colab.research.google.com/github/arddrasoni-commits/8_numpy/blob/main/Experiment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 8
## Name: Arddra Soni
## PRN: 25070123022
## Branch: ENTC
## Div. : A1
### Application of Numpy in EDA

In [7]:
import numpy as np

a = np.array ([10,20,30,40])
b = np.array([1,2,3],[4,5,6])
print(a)
print(b)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [4]:
a.ndim

1

In [ ]:
b.ndim

In [8]:
a.shape

(4,)

In [9]:
a.dtype

dtype('int64')

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
a + 2

array([12, 22, 32, 42])

In [22]:
a+5

array([15, 25, 35, 45])

In [23]:
a*2

array([20, 40, 60, 80])

In [24]:
np.mean(a)

np.float64(25.0)

In [27]:
np.median(a)
#  when mean and median is the same, data is perfect, therefore there is not "outlier"
# (a data point that differs significantly from the rest of the observations in a dataset,
# appearing as an unusually high or low value)

np.float64(25.0)

In [28]:
np.max(a)

np.int64(40)

In [29]:
np.min(a)

np.int64(10)

In [30]:
np.sum(a)

np.int64(100)

In [ ]:
# Introduction to Pandas
